name: Chef-push
on:
  pull_request:
    branch: 'master'

jobs:
  test:
    name: Kitchen test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Install pre-requisites
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install chef