name: Chef-push
on:
  push:
    branch: '!master'

jobs:
  test:
    name: Upload Cookbook
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
     - name: Install Chef
       uses: actionshub/chef-install@master
     
      - name: Get private Key
        id: pem_key
        run: |
          echo ${{ secrets.CHEF_PEM_KEY }} > .chef/validator.pem
      
      - name: Knife test
        id: test
        run: |
          knife cookbook list

    # Knife supermarket upload
      # - use knife command to upload the cookbook
    # Knife policies upload
