name: Chef-push
on:
  push:
    branch: 'master'

jobs:
  test:
    name: Upload Cookbook
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
    # Knife configure
      - Copy rsa key to pem file under .chef(pem file name is fixed)
    # Knife supermarket upload
      - use knife command to upload the cookbook
    # Knife policies upload
