name: Chef-push
on:
  push:
    branch: 
      - master

jobs:
  Upload_Cookbook:
    name: Upload Cookbook and policies
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Install Chef
        uses: actionshub/chef-install@main
  
      - name: Get private Key
        id: pem_key
        run: |
          echo "${{ secrets.CHEF_PEM_KEY }}" > .chef/prasanth155518.pem
      
      - name: Upload cookbook to supermarket
        id: cookbook_upload
        run: |
          cookbook="`echo ${{ github.event.repository.name }} | sed 's/chef-//'`"
          knife supermarket share $cookbook "Utilities" 
      
      - name: Upload policies to chef server
        id: policy_upload
        run: |
          for i in $(ls policies*/artifacts/pulse_*.tgz) ; do chef push-archive kubernetes $i; done
        
      - name: List policies
        id: policy_list
        run: |
          chef show-policy | grep "_node"