name: Cookbook Upload
on:
  workflow_dispatch:

jobs:
  Upload_Cookbook:
    name: Upload Cookbook and policies
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Install Chef
        uses: actionshub/chef-install@main
  
      - name: Get private Key
        id: pem_key
        run: |
          echo "${{ secrets.CHEF_PEM_KEY }}" > .chef/prasanth155518.pem
      
      - name: Upload cookbook to supermarket
        id: cookbook_upload
        continue-on-error: true
        run: |
          cookbook="`echo ${{ github.event.repository.name }} | sed 's/chef-//'`"
          knife supermarket share $cookbook "Utilities" 
      
      - name: Upload policies to chef server
        id: policy_upload
        continue-on-error: true
        run: |
          mkdir policies/artifacts
          for i in $(ls policies/*.rb) ; do chef install $i --chef-license accept ; chef export $i policies/artifacts -a --chef-license accept; done
          for i in $(ls policies/artifacts/*.tgz) ; do chef push-archive kubernetes $i; done
        
      - name: List policies
        id: policy_list
        run: |
          chef show-policy --chef-license accept